#include "ergodox_ez.h"
#include "action_layer.h"
#include "config.h"

enum custom_keycodes {
  PLACEHOLDER = SAFE_RANGE, // can always be here
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_ergodox(
               KC_EQUAL,KC_1,KC_2,KC_3,KC_4,KC_5,TT(2),
               CTL_T(KC_TAB),KC_Q,KC_W,KC_E,KC_R,KC_T,TT(1),
               KC_BSPACE,KC_A,KC_S,KC_D,CTL_T(KC_F),KC_G,
               KC_LSHIFT,CTL_T(KC_Z),KC_X,KC_C,KC_V,GUI_T(KC_B),SCMD_T(KC_LBRACKET),
               KC_GRAVE,KC_QUOTE,TT(2),KC_LEFT,ALT_T(KC_RIGHT),

               ALT_T(KC_APPLICATION),KC_LGUI,KC_HOME,
               KC_SPACE,KC_LCTL,KC_END,

               OSL(2),KC_6,KC_7,KC_8,KC_9,KC_0,KC_MINUS,
               OSL(1),KC_Y,KC_U,KC_I,KC_O,KC_P,KC_BSLASH,
               KC_H,CTL_T(KC_J),KC_K,KC_L,KC_SCOLON,GUI_T(KC_QUOTE),
               SCMD_T(KC_RBRACKET),GUI_T(KC_N),KC_M,KC_COMMA,KC_DOT,RCTL_T(KC_SLASH),KC_RSHIFT,
               ALT_T(KC_UP),KC_DOWN,KC_LBRACKET,KC_RBRACKET,MO(1),

               KC_LALT,CTL_T(KC_ESCAPE),KC_PGUP,KC_PGDOWN,
               KC_RCTL,KC_ENTER),

  [1] = LAYOUT_ergodox(
               KC_ESCAPE,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,LGUI(KC_GRAVE),
               KC_GRAVE,KC_EXLM,KC_AT,KC_LCBR,KC_RCBR,KC_PIPE,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_HASH,KC_DLR,KC_LPRN,KC_RPRN,KC_GRAVE,
               KC_TRANSPARENT,KC_PERC,KC_CIRC,KC_LBRACKET,KC_RBRACKET,KC_TILD,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,

               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,


               KC_TRANSPARENT,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,
               KC_TRANSPARENT,KC_UP,KC_7,KC_8,KC_9,KC_ASTR,KC_F12,
               KC_DOWN,KC_4,KC_5,KC_6,KC_PLUS,RCTL_T(KC_NO),
               KC_TRANSPARENT,KC_AMPR,KC_1,KC_2,KC_3,KC_BSLASH,KC_KP_ENTER,
               KC_TRANSPARENT,KC_DOT,KC_0,KC_EQUAL,KC_TRANSPARENT,

               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),

  [2] = LAYOUT_ergodox(
               KC_ESCAPE,KC_F1,KC_F2,KC_F3,KC_F4,KC_F5,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_WWW_BACK,KC_MS_UP,KC_WWW_FORWARD,KC_TRANSPARENT,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_LEFT,KC_MS_DOWN,KC_MS_RIGHT,KC_MS_WH_UP,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_WH_LEFT,KC_TRANSPARENT,KC_MS_WH_RIGHT,KC_MS_WH_DOWN,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MS_BTN3,KC_MS_BTN1,

               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,
               KC_MS_BTN2,KC_TRANSPARENT,KC_TRANSPARENT,

               KC_TRANSPARENT,KC_F6,KC_F7,KC_F8,KC_F9,KC_F10,KC_F11,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_F12,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MEDIA_PLAY_PAUSE,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,KC_MEDIA_PREV_TRACK,KC_MEDIA_NEXT_TRACK,KC_TRANSPARENT,KC_TRANSPARENT,
               KC_AUDIO_VOL_UP,KC_AUDIO_VOL_DOWN,KC_AUDIO_MUTE,KC_TRANSPARENT,KC_TRANSPARENT,

               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT,
               KC_TRANSPARENT,KC_TRANSPARENT,KC_TRANSPARENT),

};

const uint16_t PROGMEM fn_actions[] = {
  [1] = ACTION_LAYER_TAP_TOGGLE(1)
};

